"""Creates context model

Revision ID: 5c822c3ec84d
Revises: 
Create Date: 2025-08-30 22:06:49.934030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c822c3ec84d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('working_directory', sa.Text(), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contexts')
    # ### end Alembic commands ###
