"""creates collection model and join table

Revision ID: 9fb704dad91b
Revises: a2a3a9a69cc6
Create Date: 2025-08-30 23:06:59.769817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb704dad91b'
down_revision: Union[str, None] = 'a2a3a9a69cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spark_collections',
    sa.Column('spark_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['spark_id'], ['sparks.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spark_collections')
    # ### end Alembic commands ###
