"""creates spark-context relationship

Revision ID: a2a3a9a69cc6
Revises: 8dd10697dd05
Create Date: 2025-08-30 23:05:27.722387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a3a9a69cc6'
down_revision: Union[str, None] = '8dd10697dd05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
